name: weather_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  location: ^5.0.3
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  bloc: ^8.1.2
  meta: ^1.9.1
  geolocator: ^10.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/forest_cloudy.png
    - assets/images/forest_rainy.png
    - assets/images/forest_sunny.png
    - assets/icons/clear.png
    - assets/icons/clear@2x.png
    - assets/icons/clear@3x.png
    - assets/icons/partlysunny.png
    - assets/icons/partlysunny@2x.png
    - assets/icons/partlysunny@3x.png
    - assets/icons/rain.png
    - assets/icons/rain@2x.png
    - assets/icons/rain@3x.png
    

