name: working branch workflow

on:

  push:
    branches: 
        - '*'
        # - '!develop'
        - '!main'



jobs:

  analysis: 
    name: format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.3'
          channel: 'stable'
          architecture: x64

      # - name: Check Code Format
      #   run: dart format . --set-exit-if-changed
      
      - name: Generate code
        run: dart run build_runner build
      - name: Analyze code
        run: dart analyze .
      
 
  build:
    runs-on: ubuntu-latest
    steps:


    - name : Checkout Repo  
      uses: actions/checkout@v3
         
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name : Setup Flutter    
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.3'
        channel: 'stable'
        architecture: x64

    - name: Flutter Pub get
      run : |
          echo  flutter clean
          echo  flutter pub get

    
   

    # - name : Build Apk    
    #   run: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
    

     