name: develop branch

on:

  push:
    branches: [ develop ]



jobs:
 
  build:
    runs-on: ubuntu-latest
    steps:


    - name : Checkout Repo  
      uses: actions/checkout@v2
         
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name : Setup Flutter    
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.13.3'

    - name: Flutter Pub get
      run : |
          echo  flutter clean
          echo  flutter pub get

    - name : Flutter Analyze
      run  : flutter analyze

    
   

    - name : Build Apk    
      run: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
    

     